baseURL = "https://tichit.net/"
languageCode = "en-us"
title = "Bryce Tichit"
theme = "hugo-theme-cactus"
googleAnalytics = "G-PML7XB9NRW"
googleAnalyticsAsync = false

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2
